### ISSUE TITLE
Dependency on HAL?

### ISSUE THREAD

**Issue by Jellix** [Fabien-Chouteau/VirtAPU#2]
Hi there,

I noticed a while ago, that this little project has a dependency on HAL. I suppose, the reason is that this has been used in an embedded context with the Ada Driver's Library, but I don't think this dependency is really necessary here. After all, `Interfaces` is already used, so changing the `Tick_Count` type to derive from `Interfaces.Unsigned_32` instead of from `HAL.UInt32` removes the whole dependency from HAL.

I provided a pull request (PR #1) which would fix this, and also some other minor things with the project file.

**Comment by Fabien-Chouteau** [comment]
Merged #1, thanks
